apiVersion: v1
kind: Secret
metadata:
  name: postgres-meteo-secret
  namespace: irrigation-system
type: Opaque
data:
  # Values are base64 encoded
  # meteo_user
  postgres-username: bWV0ZW9fdXNlcg==
  # meteo_pass
  postgres-password: bWV0ZW9fcGFzcw==
  # meteodb
  postgres-database: bWV0ZW9kYg==
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-arrosage-secret
  namespace: irrigation-system
type: Opaque
data:
  # Values are base64 encoded
  # arrosage_user
  postgres-username: YXJyb3NhZ2VfdXNlcg==
  # arrosage_pass
  postgres-password: YXJyb3NhZ2VfcGFzcw==
  # arrosagedb
  postgres-database: YXJyb3NhZ2VkYg==
